version: 0.2

phases: 
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build: 
      commnads:
       - echo Build completed on `date`
       - mvn package
artifacts:
  files:
- target/VProfile.war
